name = "OptimalTrainControl"
uuid = "9439a33f-2b93-4fba-a0f8-3bebc99d821e"
authors = ["VÃ­t Fanta <fantavit@fel.cvut.cz> and contributors"]
version = "1.0.0-DEV"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DiffEqCallbacks = "~4.2.2, 4"
JSON = "~0.21.4"
Optim = "~1.11.0, 1"
OrdinaryDiffEq = "~6.90.1, 6"
RecipesBase = "~1.3.4"
Roots = "~2.2.4"
StaticArrays = "~1.9.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
