[deps]
BasicInterpolators = "26cce99e-4866-4b6d-ab74-862489e035e0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OpenStreetMapX = "86cd37e6-c0ff-550b-95fe-21d72c8d4fc9"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RailDynamics = "def5d3d9-a34b-4daf-bc22-0581843f8b2c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
