[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
BasicInterpolators = "26cce99e-4866-4b6d-ab74-862489e035e0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OpenStreetMapX = "86cd37e6-c0ff-550b-95fe-21d72c8d4fc9"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
OptimalTrainControl = "def5d3d9-a34b-4daf-bc22-0581843f8b2c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
