[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OptimalTrainControl = "9439a33f-2b93-4fba-a0f8-3bebc99d821e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
